package(default_visibility = ["//visibility:public"])

cc_library(
    name = "i386",
    srcs = [
        "writer.cpp",
    ],
    hdrs = [
        "writer.h",
    ],
    deps = [
        "//base",
        "//ir",
    ],
)

