package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lexer",
    srcs = [
        "lexer.cpp",
    ],
    hdrs = [
        "lexer.h",
        "lexer_error.h",
    ],
    deps = [
        "//base",
    ],
)
