package(default_visibility = ["//visibility:public"])

cc_library(
    name = "runtime",
    srcs = [
        "runtime.cpp",
        #"runtime/__joos_internal__/TypeInfo.java",
    ],
    hdrs = [
        "runtime.h",
    ],
    deps = [
    ],
)

