package(default_visibility = ["//visibility:public"])

# TODO: Depend on "runtime/__joos_internal__/TypeInfo.java"
cc_library(
    name = "runtime",
    srcs = [
        "runtime.cpp",
    ],
    hdrs = [
        "runtime.h",
    ],
    deps = [
    ],
)

