package(default_visibility = ["//visibility:public"])

java_test(
    name = "joostests",
    srcs = [
        "TypeInfoTest.java",
    ],
    deps = [
        "//runtime/__joos_internal__",
    ],
    main_class = "joostests.TypeInfoTest",
    size = "small",
)
