package(default_visibility = ["//visibility:public"])

exports_files([
    "Array.java",
    "StackFrame.java",
    "StringOps.java",
    "TypeInfo.java",
])

java_library(
    name = "__joos_internal__",
    srcs = [
        "Array.java",
        "StackFrame.java",
        "StringOps.java",
        "TypeInfo.java",
    ],
)
