package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = [
        "offset_table.cpp",
    ],
    hdrs = [
        "asm_writer.h",
        "offset_table.h",
    ],
    deps = [
        "//ast",
        "//base",
        "//ir",
        "//types",
    ],
)
