package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ir",
    srcs = [
        "mem.cpp",
        "mem_impl.cpp",
    ],
    hdrs = [
        "mem.h",
        "mem_impl.h",
        "stream.h",
        "stream_builder.h",
    ],
    deps = [
        "//base",
    ],
)

