package(default_visibility = ["//visibility:public"])

cc_library(
    name = "opt",
    srcs = [
        "opt.cpp",
        "peep.cpp",
        "peep.h",
    ],
    hdrs = [
        "opt.h",
    ],
    deps = [
        "//ir",
    ],
)

